parameters:
#    swm_videotek.example.class: Swm\VideotekBundle\Example

services:
#    swm_videotek.example:
#        class: %swm_videotek.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    swm_videotek.videoservice:
        class: Swm\VideotekBundle\Service\VideoService
    swm_videotek.distanthostingservice:
        class: Swm\VideotekBundle\Service\DistantHostingService
        arguments: [@swm_videotek.videoservice, %swm_videotek.path.thumbnails%, @swm_videotek.http.adapter]
    swm_videotek.http.adapter:
        class: Swm\VideotekBundle\Adapter\GuzzleAdapter

    swm_videotek.videoscrapper:
        class: Swm\VideotekBundle\Scrapper\VideoScrapper
        arguments: [%swm_videotek.keys.youtubekey%, %swm_videotek.keys.dailymotionkey%, %swm_videotek.keys.vimeokey%]

    swm_videotek.param_converter.search_query:
        class: Swm\VideotekBundle\ParamConverter\SearchQueryConverter
        tags:
            - { name: request.param_converter, converter: search_query }
    swm_videotek.listener.videonew:
        class: Swm\VideotekBundle\EventListener\VideoListener
        arguments: [@swm_videotek.videoservice]
        tags:
            - { name: kernel.event_listener, event: videotek.video.new, method:getThumb }

    swm_videotek.video.expired:
        class: Swm\VideotekBundle\Service\ExpiredVideoManager
        arguments: ['@doctrine.orm.entity_manager','@swm_videotek.distanthostingservice','@swm_videotek.videoservice']

    swm_videotek.tag.matcher:
        class: Swm\VideotekBundle\Service\TagMatcherService
        arguments: ['@doctrine.orm.entity_manager','@swm_videotek.tag.aliasgenerator']

    swm_videotek.form.tag:
        class: Swm\VideotekBundle\Form\TagType

    swm_videotek.tag.aliasgenerator:
        class: Swm\VideotekBundle\Service\TagAliasGenerator

    swm_videotek.tag.transform:
        class: Swm\VideotekBundle\Service\TagTransform

    swm_videotek.video.api.converter:
        class: Swm\VideotekBundle\Model\VideoFromApiRepository

    swm_videotek.tag.multisaver:
        class: Swm\VideotekBundle\Service\TagManager\MultiTagSaver
        arguments:
            ['@doctrine.orm.entity_manager']

    swm_videotek.cmd.populate:
        class: Swm\VideotekBundle\Service\PopulateService
        arguments:
            ['@doctrine.orm.entity_manager']