parameters:
#    swm_videotek.example.class: Swm\VideotekBundle\Example

services:
#    swm_videotek.example:
#        class: %swm_videotek.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    swm_videotek.videoservice:
        class: Swm\VideotekBundle\Service\VideoService
    swm_videotek.distanthostingservice:
        class: Swm\VideotekBundle\Service\DistantHostingService
        arguments: [@swm_videotek.videoservice, %swm_videotek.path.thumbnails%, @swm_videotek.http.adapter]
    swm_videotek.http.adapter:
        class: Swm\VideotekBundle\Adapter\GuzzleAdapter
    swm_videotek.videoscrapper:
        class: Swm\VideotekBundle\Scrapper\VideoScrapper
        arguments: [@request_stack]
    swm_videotek.param_converter.search_query:
        class: Swm\VideotekBundle\ParamConverter\SearchQueryConverter
        tags:
            - { name: request.param_converter, converter: search_query }